/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.records;


import cn.luoyanze.documentmanager.dao.tables.S1BuTB;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1BuRecord extends UpdatableRecordImpl<S1BuRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>document_manager.S1_BU.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>document_manager.S1_BU.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>document_manager.S1_BU.name</code>. 部门名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>document_manager.S1_BU.name</code>. 部门名称
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return S1BuTB.S1_BU.PRIMARY_ID;
    }

    @Override
    public Field<String> field2() {
        return S1BuTB.S1_BU.NAME;
    }

    @Override
    public Integer component1() {
        return getPrimaryId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getPrimaryId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public S1BuRecord value1(Integer value) {
        setPrimaryId(value);
        return this;
    }

    @Override
    public S1BuRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public S1BuRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S1BuRecord
     */
    public S1BuRecord() {
        super(S1BuTB.S1_BU);
    }

    /**
     * Create a detached, initialised S1BuRecord
     */
    public S1BuRecord(Integer primaryId, String name) {
        super(S1BuTB.S1_BU);

        setPrimaryId(primaryId);
        setName(name);
    }
}
