/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao;


import cn.luoyanze.documentmanager.dao.tables.S1DocTB;
import cn.luoyanze.documentmanager.dao.tables.S1OperateTB;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in document_manager.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index S1_DOC_DIR_ID = Internal.createIndex(DSL.name("dir_id"), S1DocTB.S1_DOC, new OrderField[] { S1DocTB.S1_DOC.DIR_ID }, false);
    public static final Index S1_OPERATE_DOC_ID = Internal.createIndex(DSL.name("doc_id"), S1OperateTB.S1_OPERATE, new OrderField[] { S1OperateTB.S1_OPERATE.DOC_ID }, false);
    public static final Index S1_DOC_LAST_UPDATE_USER_ID = Internal.createIndex(DSL.name("last_update_user_id"), S1DocTB.S1_DOC, new OrderField[] { S1DocTB.S1_DOC.LAST_UPDATE_USER_ID }, false);
    public static final Index S1_DOC_USER_ID = Internal.createIndex(DSL.name("user_id"), S1DocTB.S1_DOC, new OrderField[] { S1DocTB.S1_DOC.USER_ID }, false);
    public static final Index S1_OPERATE_USER_ID = Internal.createIndex(DSL.name("user_id"), S1OperateTB.S1_OPERATE, new OrderField[] { S1OperateTB.S1_OPERATE.USER_ID }, false);
}
