/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.records;


import cn.luoyanze.documentmanager.dao.tables.S1CommentTB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1CommentRecord extends UpdatableRecordImpl<S1CommentRecord> implements Record7<UInteger, String, UInteger, UInteger, String, LocalDateTime, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>document_manager.S1_COMMENT.primary_id</code>. 自增主键
     */
    public void setPrimaryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.primary_id</code>. 自增主键
     */
    public UInteger getPrimaryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.uuid</code>. UUID
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.uuid</code>. UUID
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.doc_id</code>. 文章id
     */
    public void setDocId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.doc_id</code>. 文章id
     */
    public UInteger getDocId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.user_id</code>. 用户id
     */
    public void setUserId(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.user_id</code>. 用户id
     */
    public UInteger getUserId() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.ctx</code>. 评论内容
     */
    public void setCtx(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.ctx</code>. 评论内容
     */
    public String getCtx() {
        return (String) get(4);
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.create_time</code>. 评论创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.create_time</code>. 评论创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.parent_id</code>. 上级评论
     */
    public void setParentId(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.parent_id</code>. 上级评论
     */
    public UInteger getParentId() {
        return (UInteger) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UInteger, String, UInteger, UInteger, String, LocalDateTime, UInteger> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UInteger, String, UInteger, UInteger, String, LocalDateTime, UInteger> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return S1CommentTB.S1_COMMENT.PRIMARY_ID;
    }

    @Override
    public Field<String> field2() {
        return S1CommentTB.S1_COMMENT.UUID;
    }

    @Override
    public Field<UInteger> field3() {
        return S1CommentTB.S1_COMMENT.DOC_ID;
    }

    @Override
    public Field<UInteger> field4() {
        return S1CommentTB.S1_COMMENT.USER_ID;
    }

    @Override
    public Field<String> field5() {
        return S1CommentTB.S1_COMMENT.CTX;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return S1CommentTB.S1_COMMENT.CREATE_TIME;
    }

    @Override
    public Field<UInteger> field7() {
        return S1CommentTB.S1_COMMENT.PARENT_ID;
    }

    @Override
    public UInteger component1() {
        return getPrimaryId();
    }

    @Override
    public String component2() {
        return getUuid();
    }

    @Override
    public UInteger component3() {
        return getDocId();
    }

    @Override
    public UInteger component4() {
        return getUserId();
    }

    @Override
    public String component5() {
        return getCtx();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public UInteger component7() {
        return getParentId();
    }

    @Override
    public UInteger value1() {
        return getPrimaryId();
    }

    @Override
    public String value2() {
        return getUuid();
    }

    @Override
    public UInteger value3() {
        return getDocId();
    }

    @Override
    public UInteger value4() {
        return getUserId();
    }

    @Override
    public String value5() {
        return getCtx();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public UInteger value7() {
        return getParentId();
    }

    @Override
    public S1CommentRecord value1(UInteger value) {
        setPrimaryId(value);
        return this;
    }

    @Override
    public S1CommentRecord value2(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public S1CommentRecord value3(UInteger value) {
        setDocId(value);
        return this;
    }

    @Override
    public S1CommentRecord value4(UInteger value) {
        setUserId(value);
        return this;
    }

    @Override
    public S1CommentRecord value5(String value) {
        setCtx(value);
        return this;
    }

    @Override
    public S1CommentRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public S1CommentRecord value7(UInteger value) {
        setParentId(value);
        return this;
    }

    @Override
    public S1CommentRecord values(UInteger value1, String value2, UInteger value3, UInteger value4, String value5, LocalDateTime value6, UInteger value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S1CommentRecord
     */
    public S1CommentRecord() {
        super(S1CommentTB.S1_COMMENT);
    }

    /**
     * Create a detached, initialised S1CommentRecord
     */
    public S1CommentRecord(UInteger primaryId, String uuid, UInteger docId, UInteger userId, String ctx, LocalDateTime createTime, UInteger parentId) {
        super(S1CommentTB.S1_COMMENT);

        setPrimaryId(primaryId);
        setUuid(uuid);
        setDocId(docId);
        setUserId(userId);
        setCtx(ctx);
        setCreateTime(createTime);
        setParentId(parentId);
    }
}
