/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.records;


import cn.luoyanze.documentmanager.dao.tables.S1DirTB;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1DirRecord extends UpdatableRecordImpl<S1DirRecord> implements Record5<UInteger, String, UInteger, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>document_manager.S1_DIR.primary_id</code>. 自增主键
     */
    public void setPrimaryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.primary_id</code>. 自增主键
     */
    public UInteger getPrimaryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>document_manager.S1_DIR.title</code>. 标题
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>document_manager.S1_DIR.parent_id</code>. 上级目录ID
     */
    public void setParentId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.parent_id</code>. 上级目录ID
     */
    public UInteger getParentId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>document_manager.S1_DIR.bu</code>. 所属部门
     */
    public void setBu(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.bu</code>. 所属部门
     */
    public String getBu() {
        return (String) get(3);
    }

    /**
     * Setter for <code>document_manager.S1_DIR.deep</code>. 目录层级
     */
    public void setDeep(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.deep</code>. 目录层级
     */
    public Integer getDeep() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, String, UInteger, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, String, UInteger, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return S1DirTB.S1_DIR.PRIMARY_ID;
    }

    @Override
    public Field<String> field2() {
        return S1DirTB.S1_DIR.TITLE;
    }

    @Override
    public Field<UInteger> field3() {
        return S1DirTB.S1_DIR.PARENT_ID;
    }

    @Override
    public Field<String> field4() {
        return S1DirTB.S1_DIR.BU;
    }

    @Override
    public Field<Integer> field5() {
        return S1DirTB.S1_DIR.DEEP;
    }

    @Override
    public UInteger component1() {
        return getPrimaryId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public UInteger component3() {
        return getParentId();
    }

    @Override
    public String component4() {
        return getBu();
    }

    @Override
    public Integer component5() {
        return getDeep();
    }

    @Override
    public UInteger value1() {
        return getPrimaryId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public UInteger value3() {
        return getParentId();
    }

    @Override
    public String value4() {
        return getBu();
    }

    @Override
    public Integer value5() {
        return getDeep();
    }

    @Override
    public S1DirRecord value1(UInteger value) {
        setPrimaryId(value);
        return this;
    }

    @Override
    public S1DirRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public S1DirRecord value3(UInteger value) {
        setParentId(value);
        return this;
    }

    @Override
    public S1DirRecord value4(String value) {
        setBu(value);
        return this;
    }

    @Override
    public S1DirRecord value5(Integer value) {
        setDeep(value);
        return this;
    }

    @Override
    public S1DirRecord values(UInteger value1, String value2, UInteger value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S1DirRecord
     */
    public S1DirRecord() {
        super(S1DirTB.S1_DIR);
    }

    /**
     * Create a detached, initialised S1DirRecord
     */
    public S1DirRecord(UInteger primaryId, String title, UInteger parentId, String bu, Integer deep) {
        super(S1DirTB.S1_DIR);

        setPrimaryId(primaryId);
        setTitle(title);
        setParentId(parentId);
        setBu(bu);
        setDeep(deep);
    }
}
