/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.records;


import cn.luoyanze.documentmanager.dao.tables.S1DirTB;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1DirRecord extends UpdatableRecordImpl<S1DirRecord> implements Record5<Integer, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>document_manager.S1_DIR.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>document_manager.S1_DIR.title</code>. 标题
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>document_manager.S1_DIR.parent_id</code>. 上级目录ID
     */
    public void setParentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.parent_id</code>. 上级目录ID
     */
    public Integer getParentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>document_manager.S1_DIR.bu_id</code>. 所属部门
     */
    public void setBuId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.bu_id</code>. 所属部门
     */
    public Integer getBuId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>document_manager.S1_DIR.deep</code>. 目录层级
     */
    public void setDeep(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>document_manager.S1_DIR.deep</code>. 目录层级
     */
    public Integer getDeep() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return S1DirTB.S1_DIR.PRIMARY_ID;
    }

    @Override
    public Field<String> field2() {
        return S1DirTB.S1_DIR.TITLE;
    }

    @Override
    public Field<Integer> field3() {
        return S1DirTB.S1_DIR.PARENT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return S1DirTB.S1_DIR.BU_ID;
    }

    @Override
    public Field<Integer> field5() {
        return S1DirTB.S1_DIR.DEEP;
    }

    @Override
    public Integer component1() {
        return getPrimaryId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public Integer component3() {
        return getParentId();
    }

    @Override
    public Integer component4() {
        return getBuId();
    }

    @Override
    public Integer component5() {
        return getDeep();
    }

    @Override
    public Integer value1() {
        return getPrimaryId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public Integer value3() {
        return getParentId();
    }

    @Override
    public Integer value4() {
        return getBuId();
    }

    @Override
    public Integer value5() {
        return getDeep();
    }

    @Override
    public S1DirRecord value1(Integer value) {
        setPrimaryId(value);
        return this;
    }

    @Override
    public S1DirRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public S1DirRecord value3(Integer value) {
        setParentId(value);
        return this;
    }

    @Override
    public S1DirRecord value4(Integer value) {
        setBuId(value);
        return this;
    }

    @Override
    public S1DirRecord value5(Integer value) {
        setDeep(value);
        return this;
    }

    @Override
    public S1DirRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S1DirRecord
     */
    public S1DirRecord() {
        super(S1DirTB.S1_DIR);
    }

    /**
     * Create a detached, initialised S1DirRecord
     */
    public S1DirRecord(Integer primaryId, String title, Integer parentId, Integer buId, Integer deep) {
        super(S1DirTB.S1_DIR);

        setPrimaryId(primaryId);
        setTitle(title);
        setParentId(parentId);
        setBuId(buId);
        setDeep(deep);
    }
}
