/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.records;


import cn.luoyanze.documentmanager.dao.tables.S1DocTB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1DocRecord extends UpdatableRecordImpl<S1DocRecord> implements Record10<UInteger, String, Integer, Integer, String, UInteger, LocalDateTime, String, UInteger, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>document_manager.S1_DOC.primary_id</code>. 自增主键
     */
    public void setPrimaryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.primary_id</code>. 自增主键
     */
    public UInteger getPrimaryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.permission_bu</code>. 允许的部门
     */
    public void setPermissionBu(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.permission_bu</code>. 允许的部门
     */
    public String getPermissionBu() {
        return (String) get(1);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.authority</code>. 允许的等级
     */
    public void setAuthority(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.authority</code>. 允许的等级
     */
    public Integer getAuthority() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.status</code>. 状态 0已删除， 1正常
     */
    public void setStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.status</code>. 状态 0已删除， 1正常
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.ctx</code>. 内容
     */
    public void setCtx(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.ctx</code>. 内容
     */
    public String getCtx() {
        return (String) get(4);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.user_id</code>. 创建用户id
     */
    public void setUserId(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.user_id</code>. 创建用户id
     */
    public UInteger getUserId() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.last_update_time</code>. 最近修改时间登录时间
     */
    public void setLastUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.last_update_time</code>. 最近修改时间登录时间
     */
    public LocalDateTime getLastUpdateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.title</code>. 标题
     */
    public void setTitle(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(7);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.dir_id</code>. 上级目录ID
     */
    public void setDirId(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.dir_id</code>. 上级目录ID
     */
    public UInteger getDirId() {
        return (UInteger) get(8);
    }

    /**
     * Setter for <code>document_manager.S1_DOC.last_update_user_id</code>. 最近修改用户id
     */
    public void setLastUpdateUserId(UInteger value) {
        set(9, value);
    }

    /**
     * Getter for <code>document_manager.S1_DOC.last_update_user_id</code>. 最近修改用户id
     */
    public UInteger getLastUpdateUserId() {
        return (UInteger) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UInteger, String, Integer, Integer, String, UInteger, LocalDateTime, String, UInteger, UInteger> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UInteger, String, Integer, Integer, String, UInteger, LocalDateTime, String, UInteger, UInteger> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return S1DocTB.S1_DOC.PRIMARY_ID;
    }

    @Override
    public Field<String> field2() {
        return S1DocTB.S1_DOC.PERMISSION_BU;
    }

    @Override
    public Field<Integer> field3() {
        return S1DocTB.S1_DOC.AUTHORITY;
    }

    @Override
    public Field<Integer> field4() {
        return S1DocTB.S1_DOC.STATUS;
    }

    @Override
    public Field<String> field5() {
        return S1DocTB.S1_DOC.CTX;
    }

    @Override
    public Field<UInteger> field6() {
        return S1DocTB.S1_DOC.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return S1DocTB.S1_DOC.LAST_UPDATE_TIME;
    }

    @Override
    public Field<String> field8() {
        return S1DocTB.S1_DOC.TITLE;
    }

    @Override
    public Field<UInteger> field9() {
        return S1DocTB.S1_DOC.DIR_ID;
    }

    @Override
    public Field<UInteger> field10() {
        return S1DocTB.S1_DOC.LAST_UPDATE_USER_ID;
    }

    @Override
    public UInteger component1() {
        return getPrimaryId();
    }

    @Override
    public String component2() {
        return getPermissionBu();
    }

    @Override
    public Integer component3() {
        return getAuthority();
    }

    @Override
    public Integer component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getCtx();
    }

    @Override
    public UInteger component6() {
        return getUserId();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdateTime();
    }

    @Override
    public String component8() {
        return getTitle();
    }

    @Override
    public UInteger component9() {
        return getDirId();
    }

    @Override
    public UInteger component10() {
        return getLastUpdateUserId();
    }

    @Override
    public UInteger value1() {
        return getPrimaryId();
    }

    @Override
    public String value2() {
        return getPermissionBu();
    }

    @Override
    public Integer value3() {
        return getAuthority();
    }

    @Override
    public Integer value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getCtx();
    }

    @Override
    public UInteger value6() {
        return getUserId();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdateTime();
    }

    @Override
    public String value8() {
        return getTitle();
    }

    @Override
    public UInteger value9() {
        return getDirId();
    }

    @Override
    public UInteger value10() {
        return getLastUpdateUserId();
    }

    @Override
    public S1DocRecord value1(UInteger value) {
        setPrimaryId(value);
        return this;
    }

    @Override
    public S1DocRecord value2(String value) {
        setPermissionBu(value);
        return this;
    }

    @Override
    public S1DocRecord value3(Integer value) {
        setAuthority(value);
        return this;
    }

    @Override
    public S1DocRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public S1DocRecord value5(String value) {
        setCtx(value);
        return this;
    }

    @Override
    public S1DocRecord value6(UInteger value) {
        setUserId(value);
        return this;
    }

    @Override
    public S1DocRecord value7(LocalDateTime value) {
        setLastUpdateTime(value);
        return this;
    }

    @Override
    public S1DocRecord value8(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public S1DocRecord value9(UInteger value) {
        setDirId(value);
        return this;
    }

    @Override
    public S1DocRecord value10(UInteger value) {
        setLastUpdateUserId(value);
        return this;
    }

    @Override
    public S1DocRecord values(UInteger value1, String value2, Integer value3, Integer value4, String value5, UInteger value6, LocalDateTime value7, String value8, UInteger value9, UInteger value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S1DocRecord
     */
    public S1DocRecord() {
        super(S1DocTB.S1_DOC);
    }

    /**
     * Create a detached, initialised S1DocRecord
     */
    public S1DocRecord(UInteger primaryId, String permissionBu, Integer authority, Integer status, String ctx, UInteger userId, LocalDateTime lastUpdateTime, String title, UInteger dirId, UInteger lastUpdateUserId) {
        super(S1DocTB.S1_DOC);

        setPrimaryId(primaryId);
        setPermissionBu(permissionBu);
        setAuthority(authority);
        setStatus(status);
        setCtx(ctx);
        setUserId(userId);
        setLastUpdateTime(lastUpdateTime);
        setTitle(title);
        setDirId(dirId);
        setLastUpdateUserId(lastUpdateUserId);
    }
}
