/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.records;


import cn.luoyanze.documentmanager.dao.tables.S1NoticeTB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1NoticeRecord extends UpdatableRecordImpl<S1NoticeRecord> implements Record9<UInteger, String, Integer, String, LocalDateTime, LocalDateTime, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>document_manager.S1_NOTICE.primary_id</code>. 自增主键
     */
    public void setPrimaryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.primary_id</code>. 自增主键
     */
    public UInteger getPrimaryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.uuid</code>. UUID
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.uuid</code>. UUID
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.type</code>. 内容type
     */
    public void setType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.type</code>. 内容type
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.content</code>. 内容
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.content</code>. 内容
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.start_time</code>. 起始时间
     */
    public void setStartTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.start_time</code>. 起始时间
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.end_time</code>. 结束时间
     */
    public void setEndTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.end_time</code>. 结束时间
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.accept_users</code>. 接收用户列表 逗号分隔
     */
    public void setAcceptUsers(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.accept_users</code>. 接收用户列表 逗号分隔
     */
    public String getAcceptUsers() {
        return (String) get(6);
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.accept_bu</code>. 接收部门列表, 逗号分隔
     */
    public void setAcceptBu(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.accept_bu</code>. 接收部门列表, 逗号分隔
     */
    public String getAcceptBu() {
        return (String) get(7);
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.is_global</code>. 是否全局通知 1全局
     */
    public void setIsGlobal(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.is_global</code>. 是否全局通知 1全局
     */
    public Integer getIsGlobal() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UInteger, String, Integer, String, LocalDateTime, LocalDateTime, String, String, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UInteger, String, Integer, String, LocalDateTime, LocalDateTime, String, String, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return S1NoticeTB.S1_NOTICE.PRIMARY_ID;
    }

    @Override
    public Field<String> field2() {
        return S1NoticeTB.S1_NOTICE.UUID;
    }

    @Override
    public Field<Integer> field3() {
        return S1NoticeTB.S1_NOTICE.TYPE;
    }

    @Override
    public Field<String> field4() {
        return S1NoticeTB.S1_NOTICE.CONTENT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return S1NoticeTB.S1_NOTICE.START_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return S1NoticeTB.S1_NOTICE.END_TIME;
    }

    @Override
    public Field<String> field7() {
        return S1NoticeTB.S1_NOTICE.ACCEPT_USERS;
    }

    @Override
    public Field<String> field8() {
        return S1NoticeTB.S1_NOTICE.ACCEPT_BU;
    }

    @Override
    public Field<Integer> field9() {
        return S1NoticeTB.S1_NOTICE.IS_GLOBAL;
    }

    @Override
    public UInteger component1() {
        return getPrimaryId();
    }

    @Override
    public String component2() {
        return getUuid();
    }

    @Override
    public Integer component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getContent();
    }

    @Override
    public LocalDateTime component5() {
        return getStartTime();
    }

    @Override
    public LocalDateTime component6() {
        return getEndTime();
    }

    @Override
    public String component7() {
        return getAcceptUsers();
    }

    @Override
    public String component8() {
        return getAcceptBu();
    }

    @Override
    public Integer component9() {
        return getIsGlobal();
    }

    @Override
    public UInteger value1() {
        return getPrimaryId();
    }

    @Override
    public String value2() {
        return getUuid();
    }

    @Override
    public Integer value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getContent();
    }

    @Override
    public LocalDateTime value5() {
        return getStartTime();
    }

    @Override
    public LocalDateTime value6() {
        return getEndTime();
    }

    @Override
    public String value7() {
        return getAcceptUsers();
    }

    @Override
    public String value8() {
        return getAcceptBu();
    }

    @Override
    public Integer value9() {
        return getIsGlobal();
    }

    @Override
    public S1NoticeRecord value1(UInteger value) {
        setPrimaryId(value);
        return this;
    }

    @Override
    public S1NoticeRecord value2(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public S1NoticeRecord value3(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public S1NoticeRecord value4(String value) {
        setContent(value);
        return this;
    }

    @Override
    public S1NoticeRecord value5(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public S1NoticeRecord value6(LocalDateTime value) {
        setEndTime(value);
        return this;
    }

    @Override
    public S1NoticeRecord value7(String value) {
        setAcceptUsers(value);
        return this;
    }

    @Override
    public S1NoticeRecord value8(String value) {
        setAcceptBu(value);
        return this;
    }

    @Override
    public S1NoticeRecord value9(Integer value) {
        setIsGlobal(value);
        return this;
    }

    @Override
    public S1NoticeRecord values(UInteger value1, String value2, Integer value3, String value4, LocalDateTime value5, LocalDateTime value6, String value7, String value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S1NoticeRecord
     */
    public S1NoticeRecord() {
        super(S1NoticeTB.S1_NOTICE);
    }

    /**
     * Create a detached, initialised S1NoticeRecord
     */
    public S1NoticeRecord(UInteger primaryId, String uuid, Integer type, String content, LocalDateTime startTime, LocalDateTime endTime, String acceptUsers, String acceptBu, Integer isGlobal) {
        super(S1NoticeTB.S1_NOTICE);

        setPrimaryId(primaryId);
        setUuid(uuid);
        setType(type);
        setContent(content);
        setStartTime(startTime);
        setEndTime(endTime);
        setAcceptUsers(acceptUsers);
        setAcceptBu(acceptBu);
        setIsGlobal(isGlobal);
    }
}
