/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.records;


import cn.luoyanze.documentmanager.dao.tables.S1UserTB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1UserRecord extends UpdatableRecordImpl<S1UserRecord> implements Record13<Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>document_manager.S1_USER.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>document_manager.S1_USER.account</code>. 用户账号
     */
    public void setAccount(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.account</code>. 用户账号
     */
    public String getAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>document_manager.S1_USER.password</code>. 用户密码
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.password</code>. 用户密码
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>document_manager.S1_USER.role</code>. 角色
     */
    public void setRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.role</code>. 角色
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>document_manager.S1_USER.avatar</code>. 用户头像
     */
    public void setAvatar(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.avatar</code>. 用户头像
     */
    public String getAvatar() {
        return (String) get(4);
    }

    /**
     * Setter for <code>document_manager.S1_USER.tel</code>. 电话
     */
    public void setTel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.tel</code>. 电话
     */
    public String getTel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>document_manager.S1_USER.email</code>. 电邮
     */
    public void setEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.email</code>. 电邮
     */
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>document_manager.S1_USER.last_login_time</code>. 最近一次登录时间
     */
    public void setLastLoginTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.last_login_time</code>. 最近一次登录时间
     */
    public LocalDateTime getLastLoginTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>document_manager.S1_USER.register_time</code>. 注册时间
     */
    public void setRegisterTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.register_time</code>. 注册时间
     */
    public LocalDateTime getRegisterTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>document_manager.S1_USER.status</code>. 在职状态， 在职1， 不在职0
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.status</code>. 在职状态， 在职1， 不在职0
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>document_manager.S1_USER.bu</code>. 用户部门
     */
    public void setBu(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.bu</code>. 用户部门
     */
    public String getBu() {
        return (String) get(10);
    }

    /**
     * Setter for <code>document_manager.S1_USER.authority</code>. 权限等级
     */
    public void setAuthority(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.authority</code>. 权限等级
     */
    public Integer getAuthority() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>document_manager.S1_USER.isDel</code>. 0表示正常， 1为删除
     */
    public void setIsdel(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>document_manager.S1_USER.isDel</code>. 0表示正常， 1为删除
     */
    public Integer getIsdel() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, String, Integer, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, String, Integer, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return S1UserTB.S1_USER.PRIMARY_ID;
    }

    @Override
    public Field<String> field2() {
        return S1UserTB.S1_USER.ACCOUNT;
    }

    @Override
    public Field<String> field3() {
        return S1UserTB.S1_USER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return S1UserTB.S1_USER.ROLE;
    }

    @Override
    public Field<String> field5() {
        return S1UserTB.S1_USER.AVATAR;
    }

    @Override
    public Field<String> field6() {
        return S1UserTB.S1_USER.TEL;
    }

    @Override
    public Field<String> field7() {
        return S1UserTB.S1_USER.EMAIL;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return S1UserTB.S1_USER.LAST_LOGIN_TIME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return S1UserTB.S1_USER.REGISTER_TIME;
    }

    @Override
    public Field<Integer> field10() {
        return S1UserTB.S1_USER.STATUS;
    }

    @Override
    public Field<String> field11() {
        return S1UserTB.S1_USER.BU;
    }

    @Override
    public Field<Integer> field12() {
        return S1UserTB.S1_USER.AUTHORITY;
    }

    @Override
    public Field<Integer> field13() {
        return S1UserTB.S1_USER.ISDEL;
    }

    @Override
    public Integer component1() {
        return getPrimaryId();
    }

    @Override
    public String component2() {
        return getAccount();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getRole();
    }

    @Override
    public String component5() {
        return getAvatar();
    }

    @Override
    public String component6() {
        return getTel();
    }

    @Override
    public String component7() {
        return getEmail();
    }

    @Override
    public LocalDateTime component8() {
        return getLastLoginTime();
    }

    @Override
    public LocalDateTime component9() {
        return getRegisterTime();
    }

    @Override
    public Integer component10() {
        return getStatus();
    }

    @Override
    public String component11() {
        return getBu();
    }

    @Override
    public Integer component12() {
        return getAuthority();
    }

    @Override
    public Integer component13() {
        return getIsdel();
    }

    @Override
    public Integer value1() {
        return getPrimaryId();
    }

    @Override
    public String value2() {
        return getAccount();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getRole();
    }

    @Override
    public String value5() {
        return getAvatar();
    }

    @Override
    public String value6() {
        return getTel();
    }

    @Override
    public String value7() {
        return getEmail();
    }

    @Override
    public LocalDateTime value8() {
        return getLastLoginTime();
    }

    @Override
    public LocalDateTime value9() {
        return getRegisterTime();
    }

    @Override
    public Integer value10() {
        return getStatus();
    }

    @Override
    public String value11() {
        return getBu();
    }

    @Override
    public Integer value12() {
        return getAuthority();
    }

    @Override
    public Integer value13() {
        return getIsdel();
    }

    @Override
    public S1UserRecord value1(Integer value) {
        setPrimaryId(value);
        return this;
    }

    @Override
    public S1UserRecord value2(String value) {
        setAccount(value);
        return this;
    }

    @Override
    public S1UserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public S1UserRecord value4(String value) {
        setRole(value);
        return this;
    }

    @Override
    public S1UserRecord value5(String value) {
        setAvatar(value);
        return this;
    }

    @Override
    public S1UserRecord value6(String value) {
        setTel(value);
        return this;
    }

    @Override
    public S1UserRecord value7(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public S1UserRecord value8(LocalDateTime value) {
        setLastLoginTime(value);
        return this;
    }

    @Override
    public S1UserRecord value9(LocalDateTime value) {
        setRegisterTime(value);
        return this;
    }

    @Override
    public S1UserRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public S1UserRecord value11(String value) {
        setBu(value);
        return this;
    }

    @Override
    public S1UserRecord value12(Integer value) {
        setAuthority(value);
        return this;
    }

    @Override
    public S1UserRecord value13(Integer value) {
        setIsdel(value);
        return this;
    }

    @Override
    public S1UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9, Integer value10, String value11, Integer value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S1UserRecord
     */
    public S1UserRecord() {
        super(S1UserTB.S1_USER);
    }

    /**
     * Create a detached, initialised S1UserRecord
     */
    public S1UserRecord(Integer primaryId, String account, String password, String role, String avatar, String tel, String email, LocalDateTime lastLoginTime, LocalDateTime registerTime, Integer status, String bu, Integer authority, Integer isdel) {
        super(S1UserTB.S1_USER);

        setPrimaryId(primaryId);
        setAccount(account);
        setPassword(password);
        setRole(role);
        setAvatar(avatar);
        setTel(tel);
        setEmail(email);
        setLastLoginTime(lastLoginTime);
        setRegisterTime(registerTime);
        setStatus(status);
        setBu(bu);
        setAuthority(authority);
        setIsdel(isdel);
    }
}
