/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao;


import cn.luoyanze.documentmanager.dao.tables.S1AttachTB;
import cn.luoyanze.documentmanager.dao.tables.S1BuTB;
import cn.luoyanze.documentmanager.dao.tables.S1CommentTB;
import cn.luoyanze.documentmanager.dao.tables.S1DirTB;
import cn.luoyanze.documentmanager.dao.tables.S1DocTB;
import cn.luoyanze.documentmanager.dao.tables.S1LogTB;
import cn.luoyanze.documentmanager.dao.tables.S1NodeTB;
import cn.luoyanze.documentmanager.dao.tables.S1NoticeTB;
import cn.luoyanze.documentmanager.dao.tables.S1OperateTB;
import cn.luoyanze.documentmanager.dao.tables.S1TraceTB;
import cn.luoyanze.documentmanager.dao.tables.S1UserTB;


/**
 * Convenience access to all tables in document_manager.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>document_manager.S1_ATTACH</code>.
     */
    public static final S1AttachTB S1_ATTACH = S1AttachTB.S1_ATTACH;

    /**
     * The table <code>document_manager.S1_BU</code>.
     */
    public static final S1BuTB S1_BU = S1BuTB.S1_BU;

    /**
     * The table <code>document_manager.S1_COMMENT</code>.
     */
    public static final S1CommentTB S1_COMMENT = S1CommentTB.S1_COMMENT;

    /**
     * The table <code>document_manager.S1_DIR</code>.
     */
    public static final S1DirTB S1_DIR = S1DirTB.S1_DIR;

    /**
     * The table <code>document_manager.S1_DOC</code>.
     */
    public static final S1DocTB S1_DOC = S1DocTB.S1_DOC;

    /**
     * The table <code>document_manager.S1_LOG</code>.
     */
    public static final S1LogTB S1_LOG = S1LogTB.S1_LOG;

    /**
     * The table <code>document_manager.S1_NODE</code>.
     */
    public static final S1NodeTB S1_NODE = S1NodeTB.S1_NODE;

    /**
     * The table <code>document_manager.S1_NOTICE</code>.
     */
    public static final S1NoticeTB S1_NOTICE = S1NoticeTB.S1_NOTICE;

    /**
     * The table <code>document_manager.S1_OPERATE</code>.
     */
    public static final S1OperateTB S1_OPERATE = S1OperateTB.S1_OPERATE;

    /**
     * The table <code>document_manager.S1_TRACE</code>.
     */
    public static final S1TraceTB S1_TRACE = S1TraceTB.S1_TRACE;

    /**
     * The table <code>document_manager.S1_USER</code>.
     */
    public static final S1UserTB S1_USER = S1UserTB.S1_USER;
}
