/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables;


import cn.luoyanze.documentmanager.dao.DocumentManager;
import cn.luoyanze.documentmanager.dao.Keys;
import cn.luoyanze.documentmanager.dao.tables.records.S1OperateRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1OperateTB extends TableImpl<S1OperateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>document_manager.S1_OPERATE</code>
     */
    public static final S1OperateTB S1_OPERATE = new S1OperateTB();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<S1OperateRecord> getRecordType() {
        return S1OperateRecord.class;
    }

    /**
     * The column <code>document_manager.S1_OPERATE.primary_id</code>. 自增主键
     */
    public final TableField<S1OperateRecord, UInteger> PRIMARY_ID = createField(DSL.name("primary_id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "自增主键");

    /**
     * The column <code>document_manager.S1_OPERATE.type</code>. 操作类型
     */
    public final TableField<S1OperateRecord, UInteger> TYPE = createField(DSL.name("type"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "操作类型");

    /**
     * The column <code>document_manager.S1_OPERATE.time</code>. 操作时间
     */
    public final TableField<S1OperateRecord, LocalDateTime> TIME = createField(DSL.name("time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "操作时间");

    /**
     * The column <code>document_manager.S1_OPERATE.doc_uuid</code>. 文章uuid
     */
    public final TableField<S1OperateRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.CHAR(16).nullable(false), this, "文章uuid");

    /**
     * The column <code>document_manager.S1_OPERATE.user_uuid</code>. user uuid
     */
    public final TableField<S1OperateRecord, String> USER_UUID = createField(DSL.name("user_uuid"), SQLDataType.CHAR(16).nullable(false), this, "user uuid");

    /**
     * The column <code>document_manager.S1_OPERATE.content</code>. 内容保留字段
     */
    public final TableField<S1OperateRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.VARCHAR(1024), this, "内容保留字段");

    private S1OperateTB(Name alias, Table<S1OperateRecord> aliased) {
        this(alias, aliased, null);
    }

    private S1OperateTB(Name alias, Table<S1OperateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>document_manager.S1_OPERATE</code> table reference
     */
    public S1OperateTB(String alias) {
        this(DSL.name(alias), S1_OPERATE);
    }

    /**
     * Create an aliased <code>document_manager.S1_OPERATE</code> table reference
     */
    public S1OperateTB(Name alias) {
        this(alias, S1_OPERATE);
    }

    /**
     * Create a <code>document_manager.S1_OPERATE</code> table reference
     */
    public S1OperateTB() {
        this(DSL.name("S1_OPERATE"), null);
    }

    public <O extends Record> S1OperateTB(Table<O> child, ForeignKey<O, S1OperateRecord> key) {
        super(child, key, S1_OPERATE);
    }

    @Override
    public Schema getSchema() {
        return DocumentManager.DOCUMENT_MANAGER;
    }

    @Override
    public Identity<S1OperateRecord, UInteger> getIdentity() {
        return (Identity<S1OperateRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<S1OperateRecord> getPrimaryKey() {
        return Keys.KEY_S1_OPERATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<S1OperateRecord>> getKeys() {
        return Arrays.<UniqueKey<S1OperateRecord>>asList(Keys.KEY_S1_OPERATE_PRIMARY);
    }

    @Override
    public S1OperateTB as(String alias) {
        return new S1OperateTB(DSL.name(alias), this);
    }

    @Override
    public S1OperateTB as(Name alias) {
        return new S1OperateTB(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public S1OperateTB rename(String name) {
        return new S1OperateTB(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public S1OperateTB rename(Name name) {
        return new S1OperateTB(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, UInteger, LocalDateTime, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
