/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1BuBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer primaryId;
    private String  name;

    public S1BuBO() {}

    public S1BuBO(S1BuBO value) {
        this.primaryId = value.primaryId;
        this.name = value.name;
    }

    public S1BuBO(
        Integer primaryId,
        String  name
    ) {
        this.primaryId = primaryId;
        this.name = name;
    }

    /**
     * Getter for <code>document_manager.S1_BU.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_BU.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_BU.name</code>. 部门名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>document_manager.S1_BU.name</code>. 部门名称
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1BuBO (");

        sb.append(primaryId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
