/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1CommentBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      primaryId;
    private String        uuid;
    private UInteger      docId;
    private String        ctx;
    private LocalDateTime createTime;
    private UInteger      parentId;

    public S1CommentBO() {}

    public S1CommentBO(S1CommentBO value) {
        this.primaryId = value.primaryId;
        this.uuid = value.uuid;
        this.docId = value.docId;
        this.ctx = value.ctx;
        this.createTime = value.createTime;
        this.parentId = value.parentId;
    }

    public S1CommentBO(
        UInteger      primaryId,
        String        uuid,
        UInteger      docId,
        String        ctx,
        LocalDateTime createTime,
        UInteger      parentId
    ) {
        this.primaryId = primaryId;
        this.uuid = uuid;
        this.docId = docId;
        this.ctx = ctx;
        this.createTime = createTime;
        this.parentId = parentId;
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.primary_id</code>. 自增主键
     */
    public UInteger getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.primary_id</code>. 自增主键
     */
    public void setPrimaryId(UInteger primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.uuid</code>. UUID
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.uuid</code>. UUID
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.doc_id</code>. 文章id
     */
    public UInteger getDocId() {
        return this.docId;
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.doc_id</code>. 文章id
     */
    public void setDocId(UInteger docId) {
        this.docId = docId;
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.ctx</code>. 评论内容
     */
    public String getCtx() {
        return this.ctx;
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.ctx</code>. 评论内容
     */
    public void setCtx(String ctx) {
        this.ctx = ctx;
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.create_time</code>. 评论创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.create_time</code>. 评论创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>document_manager.S1_COMMENT.parent_id</code>. 上级评论
     */
    public UInteger getParentId() {
        return this.parentId;
    }

    /**
     * Setter for <code>document_manager.S1_COMMENT.parent_id</code>. 上级评论
     */
    public void setParentId(UInteger parentId) {
        this.parentId = parentId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1CommentBO (");

        sb.append(primaryId);
        sb.append(", ").append(uuid);
        sb.append(", ").append(docId);
        sb.append(", ").append(ctx);
        sb.append(", ").append(createTime);
        sb.append(", ").append(parentId);

        sb.append(")");
        return sb.toString();
    }
}
