/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1DirBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger primaryId;
    private String   title;
    private UInteger parentId;

    public S1DirBO() {}

    public S1DirBO(S1DirBO value) {
        this.primaryId = value.primaryId;
        this.title = value.title;
        this.parentId = value.parentId;
    }

    public S1DirBO(
        UInteger primaryId,
        String   title,
        UInteger parentId
    ) {
        this.primaryId = primaryId;
        this.title = title;
        this.parentId = parentId;
    }

    /**
     * Getter for <code>document_manager.S1_DIR.primary_id</code>. 自增主键
     */
    public UInteger getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_DIR.primary_id</code>. 自增主键
     */
    public void setPrimaryId(UInteger primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_DIR.title</code>. 标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>document_manager.S1_DIR.title</code>. 标题
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>document_manager.S1_DIR.parent_id</code>. 上级目录ID
     */
    public UInteger getParentId() {
        return this.parentId;
    }

    /**
     * Setter for <code>document_manager.S1_DIR.parent_id</code>. 上级目录ID
     */
    public void setParentId(UInteger parentId) {
        this.parentId = parentId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1DirBO (");

        sb.append(primaryId);
        sb.append(", ").append(title);
        sb.append(", ").append(parentId);

        sb.append(")");
        return sb.toString();
    }
}
