/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1DirBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer primaryId;
    private String  title;
    private Integer parentId;
    private Integer buId;
    private Integer deep;

    public S1DirBO() {}

    public S1DirBO(S1DirBO value) {
        this.primaryId = value.primaryId;
        this.title = value.title;
        this.parentId = value.parentId;
        this.buId = value.buId;
        this.deep = value.deep;
    }

    public S1DirBO(
        Integer primaryId,
        String  title,
        Integer parentId,
        Integer buId,
        Integer deep
    ) {
        this.primaryId = primaryId;
        this.title = title;
        this.parentId = parentId;
        this.buId = buId;
        this.deep = deep;
    }

    /**
     * Getter for <code>document_manager.S1_DIR.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_DIR.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_DIR.title</code>. 标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>document_manager.S1_DIR.title</code>. 标题
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>document_manager.S1_DIR.parent_id</code>. 上级目录ID
     */
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * Setter for <code>document_manager.S1_DIR.parent_id</code>. 上级目录ID
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * Getter for <code>document_manager.S1_DIR.bu_id</code>. 所属部门
     */
    public Integer getBuId() {
        return this.buId;
    }

    /**
     * Setter for <code>document_manager.S1_DIR.bu_id</code>. 所属部门
     */
    public void setBuId(Integer buId) {
        this.buId = buId;
    }

    /**
     * Getter for <code>document_manager.S1_DIR.deep</code>. 目录层级
     */
    public Integer getDeep() {
        return this.deep;
    }

    /**
     * Setter for <code>document_manager.S1_DIR.deep</code>. 目录层级
     */
    public void setDeep(Integer deep) {
        this.deep = deep;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1DirBO (");

        sb.append(primaryId);
        sb.append(", ").append(title);
        sb.append(", ").append(parentId);
        sb.append(", ").append(buId);
        sb.append(", ").append(deep);

        sb.append(")");
        return sb.toString();
    }
}
