/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1DocBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      primaryId;
    private String        permissionBu;
    private Integer       authority;
    private Integer       status;
    private String        ctx;
    private UInteger      userId;
    private LocalDateTime lastUpdateTime;
    private String        title;
    private UInteger      dirId;
    private UInteger      lastUpdateUserId;

    public S1DocBO() {}

    public S1DocBO(S1DocBO value) {
        this.primaryId = value.primaryId;
        this.permissionBu = value.permissionBu;
        this.authority = value.authority;
        this.status = value.status;
        this.ctx = value.ctx;
        this.userId = value.userId;
        this.lastUpdateTime = value.lastUpdateTime;
        this.title = value.title;
        this.dirId = value.dirId;
        this.lastUpdateUserId = value.lastUpdateUserId;
    }

    public S1DocBO(
        UInteger      primaryId,
        String        permissionBu,
        Integer       authority,
        Integer       status,
        String        ctx,
        UInteger      userId,
        LocalDateTime lastUpdateTime,
        String        title,
        UInteger      dirId,
        UInteger      lastUpdateUserId
    ) {
        this.primaryId = primaryId;
        this.permissionBu = permissionBu;
        this.authority = authority;
        this.status = status;
        this.ctx = ctx;
        this.userId = userId;
        this.lastUpdateTime = lastUpdateTime;
        this.title = title;
        this.dirId = dirId;
        this.lastUpdateUserId = lastUpdateUserId;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.primary_id</code>. 自增主键
     */
    public UInteger getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.primary_id</code>. 自增主键
     */
    public void setPrimaryId(UInteger primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.permission_bu</code>. 允许的部门
     */
    public String getPermissionBu() {
        return this.permissionBu;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.permission_bu</code>. 允许的部门
     */
    public void setPermissionBu(String permissionBu) {
        this.permissionBu = permissionBu;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.authority</code>. 允许的等级
     */
    public Integer getAuthority() {
        return this.authority;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.authority</code>. 允许的等级
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.status</code>. 状态 0已删除， 1正常
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.status</code>. 状态 0已删除， 1正常
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.ctx</code>. 内容
     */
    public String getCtx() {
        return this.ctx;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.ctx</code>. 内容
     */
    public void setCtx(String ctx) {
        this.ctx = ctx;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.user_id</code>. 创建用户id
     */
    public UInteger getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.user_id</code>. 创建用户id
     */
    public void setUserId(UInteger userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.last_update_time</code>. 最近修改时间登录时间
     */
    public LocalDateTime getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.last_update_time</code>. 最近修改时间登录时间
     */
    public void setLastUpdateTime(LocalDateTime lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.title</code>. 标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.title</code>. 标题
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.dir_id</code>. 上级目录ID
     */
    public UInteger getDirId() {
        return this.dirId;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.dir_id</code>. 上级目录ID
     */
    public void setDirId(UInteger dirId) {
        this.dirId = dirId;
    }

    /**
     * Getter for <code>document_manager.S1_DOC.last_update_user_id</code>. 最近修改用户id
     */
    public UInteger getLastUpdateUserId() {
        return this.lastUpdateUserId;
    }

    /**
     * Setter for <code>document_manager.S1_DOC.last_update_user_id</code>. 最近修改用户id
     */
    public void setLastUpdateUserId(UInteger lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1DocBO (");

        sb.append(primaryId);
        sb.append(", ").append(permissionBu);
        sb.append(", ").append(authority);
        sb.append(", ").append(status);
        sb.append(", ").append(ctx);
        sb.append(", ").append(userId);
        sb.append(", ").append(lastUpdateTime);
        sb.append(", ").append(title);
        sb.append(", ").append(dirId);
        sb.append(", ").append(lastUpdateUserId);

        sb.append(")");
        return sb.toString();
    }
}
