/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1ExceptionBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       primaryId;
    private LocalDateTime time;
    private String        type;
    private String        ctx;

    public S1ExceptionBO() {}

    public S1ExceptionBO(S1ExceptionBO value) {
        this.primaryId = value.primaryId;
        this.time = value.time;
        this.type = value.type;
        this.ctx = value.ctx;
    }

    public S1ExceptionBO(
        Integer       primaryId,
        LocalDateTime time,
        String        type,
        String        ctx
    ) {
        this.primaryId = primaryId;
        this.time = time;
        this.type = type;
        this.ctx = ctx;
    }

    /**
     * Getter for <code>document_manager.S1_EXCEPTION.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_EXCEPTION.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_EXCEPTION.time</code>. 时间
     */
    public LocalDateTime getTime() {
        return this.time;
    }

    /**
     * Setter for <code>document_manager.S1_EXCEPTION.time</code>. 时间
     */
    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    /**
     * Getter for <code>document_manager.S1_EXCEPTION.type</code>. 类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>document_manager.S1_EXCEPTION.type</code>. 类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>document_manager.S1_EXCEPTION.ctx</code>. 内容
     */
    public String getCtx() {
        return this.ctx;
    }

    /**
     * Setter for <code>document_manager.S1_EXCEPTION.ctx</code>. 内容
     */
    public void setCtx(String ctx) {
        this.ctx = ctx;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1ExceptionBO (");

        sb.append(primaryId);
        sb.append(", ").append(time);
        sb.append(", ").append(type);
        sb.append(", ").append(ctx);

        sb.append(")");
        return sb.toString();
    }
}
