/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1LogBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       logid;
    private String        classname;
    private String        methodname;
    private String        exceptionname;
    private String        errmsg;
    private String        stacktrace;
    private LocalDateTime createtime;

    public S1LogBO() {}

    public S1LogBO(S1LogBO value) {
        this.logid = value.logid;
        this.classname = value.classname;
        this.methodname = value.methodname;
        this.exceptionname = value.exceptionname;
        this.errmsg = value.errmsg;
        this.stacktrace = value.stacktrace;
        this.createtime = value.createtime;
    }

    public S1LogBO(
        Integer       logid,
        String        classname,
        String        methodname,
        String        exceptionname,
        String        errmsg,
        String        stacktrace,
        LocalDateTime createtime
    ) {
        this.logid = logid;
        this.classname = classname;
        this.methodname = methodname;
        this.exceptionname = exceptionname;
        this.errmsg = errmsg;
        this.stacktrace = stacktrace;
        this.createtime = createtime;
    }

    /**
     * Getter for <code>document_manager.S1_LOG.logId</code>. 日志ID
     */
    public Integer getLogid() {
        return this.logid;
    }

    /**
     * Setter for <code>document_manager.S1_LOG.logId</code>. 日志ID
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * Getter for <code>document_manager.S1_LOG.className</code>. 类名
     */
    public String getClassname() {
        return this.classname;
    }

    /**
     * Setter for <code>document_manager.S1_LOG.className</code>. 类名
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * Getter for <code>document_manager.S1_LOG.methodName</code>. 方法名称
     */
    public String getMethodname() {
        return this.methodname;
    }

    /**
     * Setter for <code>document_manager.S1_LOG.methodName</code>. 方法名称
     */
    public void setMethodname(String methodname) {
        this.methodname = methodname;
    }

    /**
     * Getter for <code>document_manager.S1_LOG.exceptionName</code>. 异常类型
     */
    public String getExceptionname() {
        return this.exceptionname;
    }

    /**
     * Setter for <code>document_manager.S1_LOG.exceptionName</code>. 异常类型
     */
    public void setExceptionname(String exceptionname) {
        this.exceptionname = exceptionname;
    }

    /**
     * Getter for <code>document_manager.S1_LOG.errMsg</code>. 错误信息
     */
    public String getErrmsg() {
        return this.errmsg;
    }

    /**
     * Setter for <code>document_manager.S1_LOG.errMsg</code>. 错误信息
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg;
    }

    /**
     * Getter for <code>document_manager.S1_LOG.stackTrace</code>. 异常堆栈信息
     */
    public String getStacktrace() {
        return this.stacktrace;
    }

    /**
     * Setter for <code>document_manager.S1_LOG.stackTrace</code>. 异常堆栈信息
     */
    public void setStacktrace(String stacktrace) {
        this.stacktrace = stacktrace;
    }

    /**
     * Getter for <code>document_manager.S1_LOG.createTime</code>. 创建时间
     */
    public LocalDateTime getCreatetime() {
        return this.createtime;
    }

    /**
     * Setter for <code>document_manager.S1_LOG.createTime</code>. 创建时间
     */
    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1LogBO (");

        sb.append(logid);
        sb.append(", ").append(classname);
        sb.append(", ").append(methodname);
        sb.append(", ").append(exceptionname);
        sb.append(", ").append(errmsg);
        sb.append(", ").append(stacktrace);
        sb.append(", ").append(createtime);

        sb.append(")");
        return sb.toString();
    }
}
