/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1NodeBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       primaryId;
    private String        uuid;
    private String        style;
    private String        tag;
    private String        type;
    private String        parentuuid;
    private String        index;
    private String        childs;
    private String        text;
    private String        hash;
    private Integer       docId;
    private Integer       idDel;
    private LocalDateTime lastTime;

    public S1NodeBO() {}

    public S1NodeBO(S1NodeBO value) {
        this.primaryId = value.primaryId;
        this.uuid = value.uuid;
        this.style = value.style;
        this.tag = value.tag;
        this.type = value.type;
        this.parentuuid = value.parentuuid;
        this.index = value.index;
        this.childs = value.childs;
        this.text = value.text;
        this.hash = value.hash;
        this.docId = value.docId;
        this.idDel = value.idDel;
        this.lastTime = value.lastTime;
    }

    public S1NodeBO(
        Integer       primaryId,
        String        uuid,
        String        style,
        String        tag,
        String        type,
        String        parentuuid,
        String        index,
        String        childs,
        String        text,
        String        hash,
        Integer       docId,
        Integer       idDel,
        LocalDateTime lastTime
    ) {
        this.primaryId = primaryId;
        this.uuid = uuid;
        this.style = style;
        this.tag = tag;
        this.type = type;
        this.parentuuid = parentuuid;
        this.index = index;
        this.childs = childs;
        this.text = text;
        this.hash = hash;
        this.docId = docId;
        this.idDel = idDel;
        this.lastTime = lastTime;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.uuid</code>. uuid, 由前端生成
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.uuid</code>. uuid, 由前端生成
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.style</code>. dom样式
     */
    public String getStyle() {
        return this.style;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.style</code>. dom样式
     */
    public void setStyle(String style) {
        this.style = style;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.tag</code>. html标签
     */
    public String getTag() {
        return this.tag;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.tag</code>. html标签
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.type</code>. 节点类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.type</code>. 节点类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.parentUUID</code>. 父节点id
     */
    public String getParentuuid() {
        return this.parentuuid;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.parentUUID</code>. 父节点id
     */
    public void setParentuuid(String parentuuid) {
        this.parentuuid = parentuuid;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.index</code>. 层级索引
     */
    public String getIndex() {
        return this.index;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.index</code>. 层级索引
     */
    public void setIndex(String index) {
        this.index = index;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.childs</code>. 子节点列表
     */
    public String getChilds() {
        return this.childs;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.childs</code>. 子节点列表
     */
    public void setChilds(String childs) {
        this.childs = childs;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.text</code>. 文本内容
     */
    public String getText() {
        return this.text;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.text</code>. 文本内容
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.hash</code>. hash值
     */
    public String getHash() {
        return this.hash;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.hash</code>. hash值
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.doc_id</code>. 文件id
     */
    public Integer getDocId() {
        return this.docId;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.doc_id</code>. 文件id
     */
    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.id_del</code>. 是否删除 1为删除 0为未删除
     */
    public Integer getIdDel() {
        return this.idDel;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.id_del</code>. 是否删除 1为删除 0为未删除
     */
    public void setIdDel(Integer idDel) {
        this.idDel = idDel;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.last_time</code>. 上次修改时间
     */
    public LocalDateTime getLastTime() {
        return this.lastTime;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.last_time</code>. 上次修改时间
     */
    public void setLastTime(LocalDateTime lastTime) {
        this.lastTime = lastTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1NodeBO (");

        sb.append(primaryId);
        sb.append(", ").append(uuid);
        sb.append(", ").append(style);
        sb.append(", ").append(tag);
        sb.append(", ").append(type);
        sb.append(", ").append(parentuuid);
        sb.append(", ").append(index);
        sb.append(", ").append(childs);
        sb.append(", ").append(text);
        sb.append(", ").append(hash);
        sb.append(", ").append(docId);
        sb.append(", ").append(idDel);
        sb.append(", ").append(lastTime);

        sb.append(")");
        return sb.toString();
    }
}
