/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1NoticeBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       primaryId;
    private Integer       type;
    private String        content;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private String        acceptUsers;
    private String        acceptBu;
    private Integer       isGlobal;

    public S1NoticeBO() {}

    public S1NoticeBO(S1NoticeBO value) {
        this.primaryId = value.primaryId;
        this.type = value.type;
        this.content = value.content;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.acceptUsers = value.acceptUsers;
        this.acceptBu = value.acceptBu;
        this.isGlobal = value.isGlobal;
    }

    public S1NoticeBO(
        Integer       primaryId,
        Integer       type,
        String        content,
        LocalDateTime startTime,
        LocalDateTime endTime,
        String        acceptUsers,
        String        acceptBu,
        Integer       isGlobal
    ) {
        this.primaryId = primaryId;
        this.type = type;
        this.content = content;
        this.startTime = startTime;
        this.endTime = endTime;
        this.acceptUsers = acceptUsers;
        this.acceptBu = acceptBu;
        this.isGlobal = isGlobal;
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.type</code>. 内容type
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.type</code>. 内容type
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.content</code>. 内容
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.content</code>. 内容
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.start_time</code>. 起始时间
     */
    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.start_time</code>. 起始时间
     */
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.end_time</code>. 结束时间
     */
    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.end_time</code>. 结束时间
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.accept_users</code>. 接收用户列表 逗号分隔
     */
    public String getAcceptUsers() {
        return this.acceptUsers;
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.accept_users</code>. 接收用户列表 逗号分隔
     */
    public void setAcceptUsers(String acceptUsers) {
        this.acceptUsers = acceptUsers;
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.accept_bu</code>. 接收部门列表, 逗号分隔
     */
    public String getAcceptBu() {
        return this.acceptBu;
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.accept_bu</code>. 接收部门列表, 逗号分隔
     */
    public void setAcceptBu(String acceptBu) {
        this.acceptBu = acceptBu;
    }

    /**
     * Getter for <code>document_manager.S1_NOTICE.is_global</code>. 是否全局通知 1全局
     */
    public Integer getIsGlobal() {
        return this.isGlobal;
    }

    /**
     * Setter for <code>document_manager.S1_NOTICE.is_global</code>. 是否全局通知 1全局
     */
    public void setIsGlobal(Integer isGlobal) {
        this.isGlobal = isGlobal;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1NoticeBO (");

        sb.append(primaryId);
        sb.append(", ").append(type);
        sb.append(", ").append(content);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(acceptUsers);
        sb.append(", ").append(acceptBu);
        sb.append(", ").append(isGlobal);

        sb.append(")");
        return sb.toString();
    }
}
