/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1NodeBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        uuid;
    private String        style;
    private String        class_;
    private String        attribute;
    private String        tag;
    private String        type;
    private String        parentuuid;
    private String        index;
    private String        text;
    private String        hash;
    private Integer       docId;
    private Integer       isDel;
    private LocalDateTime lastTime;

    public S1NodeBO() {}

    public S1NodeBO(S1NodeBO value) {
        this.uuid = value.uuid;
        this.style = value.style;
        this.class_ = value.class_;
        this.attribute = value.attribute;
        this.tag = value.tag;
        this.type = value.type;
        this.parentuuid = value.parentuuid;
        this.index = value.index;
        this.text = value.text;
        this.hash = value.hash;
        this.docId = value.docId;
        this.isDel = value.isDel;
        this.lastTime = value.lastTime;
    }

    public S1NodeBO(
        String        uuid,
        String        style,
        String        class_,
        String        attribute,
        String        tag,
        String        type,
        String        parentuuid,
        String        index,
        String        text,
        String        hash,
        Integer       docId,
        Integer       isDel,
        LocalDateTime lastTime
    ) {
        this.uuid = uuid;
        this.style = style;
        this.class_ = class_;
        this.attribute = attribute;
        this.tag = tag;
        this.type = type;
        this.parentuuid = parentuuid;
        this.index = index;
        this.text = text;
        this.hash = hash;
        this.docId = docId;
        this.isDel = isDel;
        this.lastTime = lastTime;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.uuid</code>. uuid, 由前端生成
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.uuid</code>. uuid, 由前端生成
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.style</code>. dom样式
     */
    public String getStyle() {
        return this.style;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.style</code>. dom样式
     */
    public void setStyle(String style) {
        this.style = style;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.class</code>. class
     */
    public String getClass_() {
        return this.class_;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.class</code>. class
     */
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.attribute</code>. 其他的attribute，json格式，map接收
     */
    public String getAttribute() {
        return this.attribute;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.attribute</code>. 其他的attribute，json格式，map接收
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.tag</code>. html标签
     */
    public String getTag() {
        return this.tag;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.tag</code>. html标签
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.type</code>. 节点类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.type</code>. 节点类型
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.parentUUID</code>. 父节点id
     */
    public String getParentuuid() {
        return this.parentuuid;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.parentUUID</code>. 父节点id
     */
    public void setParentuuid(String parentuuid) {
        this.parentuuid = parentuuid;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.index</code>. 层级索引
     */
    public String getIndex() {
        return this.index;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.index</code>. 层级索引
     */
    public void setIndex(String index) {
        this.index = index;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.text</code>. 文本内容
     */
    public String getText() {
        return this.text;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.text</code>. 文本内容
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.hash</code>. hash值
     */
    public String getHash() {
        return this.hash;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.hash</code>. hash值
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.doc_id</code>. 文件id
     */
    public Integer getDocId() {
        return this.docId;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.doc_id</code>. 文件id
     */
    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.is_del</code>. 是否删除 1为删除 0为未删除
     */
    public Integer getIsDel() {
        return this.isDel;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.is_del</code>. 是否删除 1为删除 0为未删除
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * Getter for <code>document_manager.S1_NODE.last_time</code>. 上次修改时间
     */
    public LocalDateTime getLastTime() {
        return this.lastTime;
    }

    /**
     * Setter for <code>document_manager.S1_NODE.last_time</code>. 上次修改时间
     */
    public void setLastTime(LocalDateTime lastTime) {
        this.lastTime = lastTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1NodeBO (");

        sb.append(uuid);
        sb.append(", ").append(style);
        sb.append(", ").append(class_);
        sb.append(", ").append(attribute);
        sb.append(", ").append(tag);
        sb.append(", ").append(type);
        sb.append(", ").append(parentuuid);
        sb.append(", ").append(index);
        sb.append(", ").append(text);
        sb.append(", ").append(hash);
        sb.append(", ").append(docId);
        sb.append(", ").append(isDel);
        sb.append(", ").append(lastTime);

        sb.append(")");
        return sb.toString();
    }
}
