/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1OperateBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       primaryId;
    private Integer       type;
    private LocalDateTime time;
    private Integer       docId;
    private Integer       userId;
    private String        content;

    public S1OperateBO() {}

    public S1OperateBO(S1OperateBO value) {
        this.primaryId = value.primaryId;
        this.type = value.type;
        this.time = value.time;
        this.docId = value.docId;
        this.userId = value.userId;
        this.content = value.content;
    }

    public S1OperateBO(
        Integer       primaryId,
        Integer       type,
        LocalDateTime time,
        Integer       docId,
        Integer       userId,
        String        content
    ) {
        this.primaryId = primaryId;
        this.type = type;
        this.time = time;
        this.docId = docId;
        this.userId = userId;
        this.content = content;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.primary_id</code>. 自增主键
     */
    public Integer getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.primary_id</code>. 自增主键
     */
    public void setPrimaryId(Integer primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.type</code>. 操作类型
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.type</code>. 操作类型
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.time</code>. 操作时间
     */
    public LocalDateTime getTime() {
        return this.time;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.time</code>. 操作时间
     */
    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.doc_id</code>. 文章uuid
     */
    public Integer getDocId() {
        return this.docId;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.doc_id</code>. 文章uuid
     */
    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.user_id</code>. user uuid
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.user_id</code>. user uuid
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.content</code>. 内容保留字段
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.content</code>. 内容保留字段
     */
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1OperateBO (");

        sb.append(primaryId);
        sb.append(", ").append(type);
        sb.append(", ").append(time);
        sb.append(", ").append(docId);
        sb.append(", ").append(userId);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
