/*
 * This file is generated by jOOQ.
 */
package cn.luoyanze.documentmanager.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S1OperateBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger      primaryId;
    private UInteger      type;
    private LocalDateTime time;
    private String        docUuid;
    private String        userUuid;
    private String        content;

    public S1OperateBO() {}

    public S1OperateBO(S1OperateBO value) {
        this.primaryId = value.primaryId;
        this.type = value.type;
        this.time = value.time;
        this.docUuid = value.docUuid;
        this.userUuid = value.userUuid;
        this.content = value.content;
    }

    public S1OperateBO(
        UInteger      primaryId,
        UInteger      type,
        LocalDateTime time,
        String        docUuid,
        String        userUuid,
        String        content
    ) {
        this.primaryId = primaryId;
        this.type = type;
        this.time = time;
        this.docUuid = docUuid;
        this.userUuid = userUuid;
        this.content = content;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.primary_id</code>. 自增主键
     */
    public UInteger getPrimaryId() {
        return this.primaryId;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.primary_id</code>. 自增主键
     */
    public void setPrimaryId(UInteger primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.type</code>. 操作类型
     */
    public UInteger getType() {
        return this.type;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.type</code>. 操作类型
     */
    public void setType(UInteger type) {
        this.type = type;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.time</code>. 操作时间
     */
    public LocalDateTime getTime() {
        return this.time;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.time</code>. 操作时间
     */
    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.doc_uuid</code>. 文章uuid
     */
    public String getDocUuid() {
        return this.docUuid;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.doc_uuid</code>. 文章uuid
     */
    public void setDocUuid(String docUuid) {
        this.docUuid = docUuid;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.user_uuid</code>. user uuid
     */
    public String getUserUuid() {
        return this.userUuid;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.user_uuid</code>. user uuid
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }

    /**
     * Getter for <code>document_manager.S1_OPERATE.content</code>. 内容保留字段
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>document_manager.S1_OPERATE.content</code>. 内容保留字段
     */
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S1OperateBO (");

        sb.append(primaryId);
        sb.append(", ").append(type);
        sb.append(", ").append(time);
        sb.append(", ").append(docUuid);
        sb.append(", ").append(userUuid);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
